### ISSUE TITLE
Algeria bug

### ISSUE THREAD

**Issue by Supercorvax** [NilsJTM/TNOcustompaths#5]
I've found and corrected the reason for the Algeria rule not working properly. Add the file below to the mod, event IBR.4106 was altered.
[TNO_IberiaEvents.txt](https://github.com/NilsJTM/TNOcustompaths/files/7231008/TNO_IberiaEvents.txt)
.

**Comment by Supercorvax** [comment]
Also, add this to the event files:



[TNO_Cheat.txt](https://github.com/NilsJTM/TNOcustompaths/files/7231644/TNO_Cheat.txt)

UPD: btw... this mod is the reason I decided to finally try TNO

**Comment by NilsJTM** [comment]
Sorry for the very late response. For now the Algerian rule is removed, but we'll get back to adding it again at some point. 
Will take your solution in mind.
